networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - app
      - api
      - site
      - cms
      - cmsdb
      - apidb
    networks:
      - dev

  cmsdb:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${APIDB_NAME}
    volumes:
      - cmsdb-data:/var/lib/postgresql/data
    networks:
      - dev

  apidb:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${CMSDB_NAME}
    volumes:
      - apidb-data:/var/lib/postgresql/data
    networks:
      - dev

  app:
    build:
      context: ./cicd-app
    networks:
      - dev
    env_file:
      - ./cicd-app/.env

  api:
    build:
      context: ./cicd-api
    depends_on:
      - apidb
    networks:
      - dev
    env_file:
      - ./cicd-api/.env

  site:
    build:
      context: ./cicd-site
    networks:
      - dev
    env_file:
      - ./cicd-site/.env

  cms:
    build:
      context: ./cdcd-cms
    depends_on:
      - cmsdb
    networks:
      - dev
    env_file:
      - ./cdcd-cms/.env

volumes:
  cmsdb-data:
  apidb-data:
